language: android

jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

  licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
script:
- "./gradlew assembleDebug"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
